"""Migración inicial limpia

Revision ID: 7cc0e9aab701
Revises: 
Create Date: 2026-01-05 02:40:32.991035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc0e9aab701'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
   
    
   
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint(None, 'puntos_espera', type_='unique')
    op.drop_constraint(None, 'puntos_espera', type_='unique')
    
    op.create_index(op.f('idx_conductores_codigo'), 'conductores', ['codigo'], unique=1)
    
    
    # ### end Alembic commands ###
