"""Agregar tolerancia dinamica y limpiar campos antiguos

Revision ID: 19f7f775e336
Revises: b28eec6de4c8
Create Date: 2026-08-12 22:56:59.214531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f7f775e336'
down_revision = 'b28eec6de4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.alter_column('tolerancia_dinamica_minutos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(15)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.alter_column('tolerancia_dinamica_minutos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(15)'))

    # ### end Alembic commands ###
