"""Agregar campos de geolocalización a Conductor

Revision ID: 2de7b78c8863
Revises: a7f7574aff0a
Create Date: 2026-06-04 22:02:08.454959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de7b78c8863'
down_revision = 'a7f7574aff0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.drop_column('ultima_actualizacion')
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    # ### end Alembic commands ###
