"""eliminar_tabla_operaciones_pendientes

Revision ID: 346d4419bbd9
Revises: 7875fcc1e8c7
Create Date: 2026-07-22 00:00:25.102547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346d4419bbd9'
down_revision = '7875fcc1e8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operaciones_pendientes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operaciones_pendientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conductor_id', sa.INTEGER(), nullable=True),
    sa.Column('origen', sa.VARCHAR(length=20), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conductor_id')
    )
    # ### end Alembic commands ###
