"""Migracion conductores con tiempo de expiracion

Revision ID: 4b16f57af7a0
Revises: 346d4419bbd9
Create Date: 2026-08-03 18:22:21.300348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b16f57af7a0'
down_revision = '346d4419bbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('lista_espera_multiple')
    with op.batch_alter_table('cola_despachos', schema=None) as batch_op:
        batch_op.drop_column('nro_autos')
        batch_op.drop_column('punto_id')

    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('expiracion_gps',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_conductores_telegram_id', ['telegram_id'])

    with op.batch_alter_table('cuotas_semanales', schema=None) as batch_op:
        batch_op.create_unique_constraint('_conductor_semana_uc', ['conductor_id', 'semana_anio'])

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('punto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('punto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cuotas_semanales', schema=None) as batch_op:
        batch_op.drop_constraint('_conductor_semana_uc', type_='unique')

    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('expiracion_gps',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('telegram_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('cola_despachos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punto_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('nro_autos', sa.INTEGER(), server_default=sa.text('1'), nullable=False))

    #op.create_table('lista_espera_multiple',
    #sa.Column('id_lista_multiple', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('iteraciones', sa.INTEGER(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    #sa.PrimaryKeyConstraint('id_lista_multiple')
    
    # ### end Alembic commands ###
