"""migracion_unificada_enero

Revision ID: 6d7d1b77fc6a
Revises: ab8ec844675c
Create Date: 2026-01-11 11:55:34.389620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7d1b77fc6a'
down_revision = 'ab8ec844675c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_autos')
    with op.batch_alter_table('autos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Disponible'"))

    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_conductores_codigo'))
        batch_op.create_unique_constraint('uq_conductores_codigo', ['codigo'])

    with op.batch_alter_table('despachos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('origen_despacho',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_despachos_grupo_id'), ['grupo_id'], unique=False)
        # CAMBIO: Se agregó nombre 'fk_despachos_grupos'
        batch_op.create_foreign_key('fk_despachos_grupos', 'grupos', ['grupo_id'], ['grupo_id'])
        batch_op.drop_column('destino_despacho')

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punto_id', sa.Integer(), nullable=True))
        # CAMBIO: Se agregó nombre 'fk_turnos_puntos'
        batch_op.create_foreign_key('fk_turnos_puntos', 'puntos_espera', ['punto_id'], ['id_punto'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        # CAMBIO: Se agregó nombre 'fk_turnos_puntos'
        batch_op.drop_constraint('fk_turnos_puntos', type_='foreignkey')
        batch_op.drop_column('punto_id')

    with op.batch_alter_table('despachos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino_despacho', sa.VARCHAR(length=100), nullable=False))
        # CAMBIO: Se agregó nombre 'fk_despachos_grupos'
        batch_op.drop_constraint('fk_despachos_grupos', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_despachos_grupo_id'))
        batch_op.alter_column('origen_despacho',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('grupo_id')

    with op.batch_alter_table('conductores', schema=None) as batch_op:
        # CAMBIO: Se agregó nombre 'uq_conductores_codigo'
        batch_op.drop_constraint('uq_conductores_codigo', type_='unique')
        batch_op.create_index(batch_op.f('idx_conductores_codigo'), ['codigo'], unique=1)
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('autos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Disponible'"))

    op.create_table('_alembic_tmp_autos',
    sa.Column('id_auto', sa.INTEGER(), nullable=False),
    sa.Column('nro_placa', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tipo_auto', sa.VARCHAR(length=50), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=50), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Disponible'"), nullable=False),
    sa.PrimaryKeyConstraint('id_auto'),
    sa.UniqueConstraint('nro_placa')
    )
    # ### end Alembic commands ###
