"""Versión estable v1.2

Revision ID: 72282fb0ee01
Revises: 6d7d1b77fc6a
Create Date: 2026-01-19 17:43:58.312501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72282fb0ee01'
down_revision = '6d7d1b77fc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_auditoria_accesos')
    with op.batch_alter_table('auditoria_accesos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('usuario',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('evento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('cola_despachos', schema=None) as batch_op:
        batch_op.alter_column('origen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('destino',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('punto_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('punto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cola_despachos', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('destino',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('origen',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('auditoria_accesos', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('evento',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('usuario',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_auditoria_accesos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('evento', sa.VARCHAR(length=20), nullable=False),
    sa.Column('fecha_hora', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), nullable=True),
    sa.Column('usuario_nombre', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
