"""Agregar columna telegram_id a conductores

Revision ID: 7875fcc1e8c7
Revises: 887eb28a7110
Create Date: 2026-06-13 14:24:49.805318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7875fcc1e8c7'
down_revision = '887eb28a7110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        # Cambiado None por un nombre de restricción
        batch_op.create_unique_constraint('uq_conductores_telegram_id', ['telegram_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        # Cambiado None por el mismo nombre de restricción
        batch_op.drop_constraint('uq_conductores_telegram_id', type_='unique')
        batch_op.alter_column('telegram_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###

    # ### end Alembic commands ###
