"""Agregar columna telegram_id a conductores

Revision ID: 887eb28a7110
Revises: 2de7b78c8863
Create Date: 2026-06-13 14:17:30.760492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887eb28a7110'
down_revision = '2de7b78c8863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
