"""gestion de cuotas semanales conductores

Revision ID: a7f7574aff0a
Revises: 70f723c0aa23
Create Date: 2026-05-20 07:09:46.613886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f7574aff0a'
down_revision = '70f723c0aa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuotas_semanales_test')
    with op.batch_alter_table('cuotas_semanales', schema=None) as batch_op:
        batch_op.create_unique_constraint('_conductor_semana_uc', ['conductor_id', 'semana_anio'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuotas_semanales', schema=None) as batch_op:
        batch_op.drop_constraint('_conductor_semana_uc', type_='unique')

    op.create_table('cuotas_semanales_test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conductor_id', sa.INTEGER(), nullable=False),
    sa.Column('semana_anio', sa.VARCHAR(length=10), nullable=False),
    sa.Column('monto_fijo', sa.FLOAT(), nullable=True),
    sa.Column('pagado', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_pago', sa.DATETIME(), nullable=True),
    sa.Column('referencia_pago', sa.VARCHAR(length=50), nullable=True),
    sa.Column('es_exonerado', sa.BOOLEAN(), nullable=True),
    sa.Column('tipo_novedad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('observaciones', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductores.id_conductor'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
