"""agregar alerta_enviada

Revision ID: b28eec6de4c8
Revises: 4b16f57af7a0
Create Date: 2026-08-11 15:30:28.335959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28eec6de4c8'
down_revision = '4b16f57af7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerta_enviada', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('punto_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('punto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.drop_column('alerta_enviada')

    # ### end Alembic commands ###
