"""Migración base estable

Revision ID: d265422ede41
Revises: 
Create Date: 2026-05-06 19:35:32.958415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd265422ede41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.drop_table('lista_espera_multiple')
    with op.batch_alter_table('cola_despachos', schema=None) as batch_op:
        batch_op.alter_column('origen',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('destino',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('punto_id')
        batch_op.drop_column('nro_autos')

    with op.batch_alter_table('despachos', schema=None) as batch_op:
        batch_op.alter_column('destino_despacho',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('incidencias', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('matriz_tarifas', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('destino',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('precio_cop',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('punto_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.alter_column('punto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('matriz_tarifas', schema=None) as batch_op:
        batch_op.alter_column('precio_cop',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('destino',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('incidencias', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('despachos', schema=None) as batch_op:
        batch_op.alter_column('destino_despacho',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('cola_despachos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nro_autos', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('punto_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('destino',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('origen',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    op.create_table('lista_espera_multiple',
    sa.Column('id_lista_multiple', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('iteraciones', sa.INTEGER(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_lista_multiple')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
