"""init schema con tarifa

Revision ID: e13002087902
Revises: 
Create Date: 2025-12-05 11:04:26.342005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13002087902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_espera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=255), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('hora', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('nro_telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lista_espera')
    # ### end Alembic commands ###
