"""add punto_referencia to clientes

Revision ID: ab8ec844675c
Revises: 3cd198268e33
Create Date: 2025-12-12 14:59:23.736533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8ec844675c'
down_revision = '3cd198268e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punto_referencia', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('punto_referencia')
    # ### end Alembic commands ###
